# Generated by Django 5.2.12 on 2026-03-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationanalytics',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='notifications.notification'),
        ),
        migrations.AddIndex(
            model_name='notificationanalytics',
            index=models.Index(fields=['notification', 'event_type'], name='notificatio_notific_ead136_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationanalytics',
            index=models.Index(fields=['created_at'], name='notificatio_created_6ef1e3_idx'),
        ),
    ]
